const products = [
  {
    id: 1,
    subject: 'UI UX Design',
    price: 400,
    quantity: 6,
    image: 'img/UI UX Design.jpg',
    cartquantity: 0,
  },
  {
    id: 2,
    subject: 'WEB Designing',
    price: 400,
    quantity: 4,
    image: 'img/web design.jpg',
    cartquantity: 0,
  },
  {
    id: 3,
    subject: 'WEB Engineering',
    price: 550,
    quantity: 8,
    image: 'img/Web Engineering.jpg',
    cartquantity: 0,
  },
  {
    id: 4,
    subject: 'Android Studio',
    price: 300,
    quantity: 6,
    image: 'img/Android .jpg',
    cartquantity: 0,
  },
  {
    id: 5,
    subject: 'Graphic Designing',
    price: 350,
    quantity: 5,
    image: 'img/graffic designing.jpg',
    cartquantity: 0,
  },
  {
    id: 6,
    subject: 'IOS Development',
    price: 450,
    quantity: 7,
    image: 'img/Ios Dev.jpg',
    cartquantity: 0,
  },
  {
    id: 7,
    subject: 'MS Office',
    price: 550,
    quantity: 7,
    image: 'img/ms office.png',
    cartquantity: 0,
  },
  {
    id: 8,
    subject: 'linux Red hat course',
    price: 650,
    quantity: 6,
    image: 'img/download.jpg',
    cartquantity: 0,
  },
  {
    id: 9,
    subject: 'vfx design',
    price: 700,
    quantity: 9,
    image: 'img/VFX Design.jpg',
    cartquantity: 0,
  },
  {
    id: 10,
    subject: 'Asp.Net',
    price: 150,
    quantity: 6,
    image: 'img/asp.netcourse.jpg',
    cartquantity: 0,
  },
];